name: CI Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Yarn test 
        run: yarn install && CI=true yarn test
        working-directory: .
      - name: Yarn audit
        run: yarn audit --groups dependencies optionalDependencies --level high
        working-directory: .

