name: CI Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: CI=true yarn test && yarn install
        working-directory: .
